[Variables]

;open yahoo.com/news/weather and copy your location
;e.g: "saudi-arabia/riyadh/riyadh-22725955".... you can see how here: https://i.imgur.com/JwwXetb.png
;and put it in the locationCode underneath :)

LocationCode=saudi-arabia/riyadh/riyadh-22725984


;I know what you're thinking about but sadly you can't currently change 
;the source website which is currently "yahoo.com", so pls to keep your
;skin working correctly leave the section bellow the line:)

___________________________DON'T TOUCH__________________________
URL=https://www.yahoo.com/news/weather/#LocationCode#
Language=en-GB
