# PANEL METRICS

[Variables]
Imagedir=#SKINSPATH#WP7\@Resources\Common\Panel\Default
Overlay=none

Globalblurenable=0
Blurtype=1
Blurcornerradius=0
Padding=0

ColorSkin=30,30,30
ColorSkin2=50,50,50

Opacity=240
Opacity2=240

TextColor=255,255,255
TextColor2=255,255,255


PanelTitleOpacity=255
Shadow=shadow
ItemShadowColor=0,0,0,20
Align=left
Xposition=10
DefaultFontSize=(#Height#/15)
Yposition=1.2

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light
centertextOn=0
Angle=0
PanelTitleOpacity2=255
PanelLabels=0
