[Variables]

Bands=22
; Number of peaks - Activate Ocean\GenerateBands.ini skin after changing this value

Color=255,255,255,200

Width=1700
Height=240

LineWidth=2

AverageSize=2
; Average sound levels over time to provide continuity

LoudnessEqualization=0
; Increases visibility for quiet audio sources when applicable

FFTSize=7168
FFTOverlap="(#FFTSize#-256)"
FFTAttack=0
FFTDecay=300
FreqMin=20
FreqMax=20000
Sensitivity=37
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel

MusicPlayer=Spotify
; Music player process name

FirstBandIndex=1

; Environment variables for settings window
SkinGroup=Ocean
Config=WP7\Ocean
ConfigPath=C:\Users\Abdelrahman 20050\Documents\Rainmeter\Skins\WP7\Ocean\Ocean.ini
WriteVariable=Color
LineOnly=0
Angle=0
Invert=0
Channel=Avg
Port=Output
ID=
