# PANEL METRICS

[Variables]
Imagedir=C:\Users\Abdelrahman 20050\Documents\Rainmeter\Skins\#ROOTCONFIG#\@Resources\Common\Panel\Default
Overlay=iphone

Globalblurenable=0
Blurtype=1
Blurcornerradius=0
Padding=5
Win10Blur=none
ColorSkin=174,174,174
ColorSkin2=245,245,245

Opacity=25
Opacity2=200

TextColor=255,255,255
TextColor2=255,255,255


PanelTitleOpacity=255
Shadow=Shadow
ItemShadowColor=0,0,0,20
Align=left
Xposition=15
DefaultFontSize=(#Height#/15)
Yposition=1.2

FontType=Glacial Indifference Bold
FontTypeWP=Lato Regular
FontFaceUI=Segoe UI
FontFaceLight=Open Sans Condensed Light
centertextOn=1
Angle=0
PanelTitleOpacity2=255
PanelLabels=0
metric=0
